# Build information
- build:       mysql_commando
  description: Build project mysql_commando
  extends:     ':python:python.yml'
  default:     [clean, test]
  alias:
    test:
    - check_env
    - py_test
    release:
    - py_clean
    - test
    - dist
    - upload
    - tag

# Build properties
- properties:
    name:        mysql_commando
    package:     :name
    version:     "0.4.1"
    author:      "Michel Casabianca"
    email:       "casa@sweetohm.net"
    license:     "Apache Software License"
    description: "mysql_commando is a lightweight MySQL driver"
    py_src_dir:  :name
    py_chk_src:  :name
    py_chk_cfg:  "pylint.cfg"
    py_test_dir: "#{name}/test"
    py_clean_files:
    - "**/*.pyc"
    - "**/*.pyo"
    - "setup.py"
    - "MANIFEST"

# Build targets
- target:      check_env
  description: Check that we are running in the project's Virtualenv
  script:
  - if: "`which python` !~ /^#{base}\/env\/bin\/python$/"
    then:
    - raise: "You are not running in the project's Virtualenv, aborting"
    else:
    - print: "You are running in the project's Virtualenv, please proceed"

- target:      setup
  description: Generate setup file
  script:
  - erb:
      src:  "setup.py.erb"
      dest: "setup.py"

- target:      dist
  depends:     setup
  description: Generate distribution archive
  script:
  - mkdir: :py_build_dir
  - "python setup.py sdist -d #{py_build_dir}"

- target:      upload
  depends:     setup
  description: Upload the distribution
  script:
  - mkdir: :py_build_dir
  - "python setup.py sdist -d #{py_build_dir} register upload"

- target:      tag
  description: Tag the release
  script:
  - "git tag -a 'RELEASE-#{version}' -m 'Release #{version}'"
