# Build information
- build:       mysql_null_driver
  description: Build project mysql_null_driver
  extends:     ':python:python.yml'
  default:     [clean, test]
  alias:
    release:
    - py_clean
    - py_test
    - dist
    - upload
    - tag

# Build properties
- properties:
    name:        mysql_null_driver
    package:     :name
    version:     "0.3.1"
    author:      "Michel Casabianca"
    email:       "casa@sweetohm.net"
    license:     "Apache Software License"
    description: "Mysql_null_driver is a lightweight MySQL driver"
    py_src_dir:  :name
    py_chk_src:  :name
    py_chk_cfg:  "pylint.cfg"
    py_test_dir: "#{name}/test"
    py_clean_files:
    - "**/*.pyc"
    - "**/*.pyo"
    - "setup.py"
    - "README"
    - "MANIFEST"

# Build targets
- target:      setup                                                                                                                                                 
  description: Generate setup file
  script:
  - erb:
      src:  "setup.py.erb"
      dest: "setup.py"

- target:      readme
  description: Generate README for pypi
  script:
  - "pandoc -f markdown -t rst -o README"

- target:      dist
  depends:     [setup, readme]
  description: Generate distribution archive
  script:
  - mkdir: :py_build_dir
  - "python setup.py sdist -d #{py_build_dir}"

- target:      upload
  depends:     setup
  description: Upload the distribution
  script:
  - mkdir: :py_build_dir
  - "python setup.py sdist -d #{py_build_dir} register upload"

- target:      tag
  description: Tag the release
  script:
  - "git tag -a 'RELEASE-#{version}' -m 'Release #{version}'"

